sudo: required
services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/click-count

deploy:
 provider: script
 skip_cleanup: true
 script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_USERNAME/click-count
 on:
   branch: master

after_script:
  docker image -ls