apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    k8s-app: simple
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: simple
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - name: http
              containerPort: 6379
